- name: Initialize the Kubernetes cluster using kubeadm
  become: yes
  #command: kubeadm init --pod-network-cidr={{pod_network_cidr}} --apiserver-advertise-address="{{master_ip}}"
  command: kubeadm init --apiserver-advertise-address="{{master_ip}}" --apiserver-cert-extra-sans="{{master_ip}}"  --node-name k8s-master --pod-network-cidr={{pod_network_cidr}}
  ignore_errors: yes
- name: initfile
  copy:
    content: kubeadm init --apiserver-advertise-address="{{master_ip}}" --apiserver-cert-extra-sans="{{master_ip}}"  --node-name k8s-master --pod-network-cidr={{pod_network_cidr}}
    dest: /tmp/k8s_initcommand
#- name: Setup kubeconfig for vagrant user
#  command: "{{ item }}"
#  with_items:
#     - mkdir -p /home/ubuntu/.kube
#     - cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
#     - chown ubuntu:ubuntu /home/ubuntu/.kube/config
- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command
#- name: Install calico pod network
#  become: false
#  #command: kubectl create -f https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml
#  #https://docs.projectcalico.org/manifests/calico-typha.yaml
#  command: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
#  #ignore_errors: yes
##- name: Generate join command
##  command: kubeadm token create --print-join-command
##  register: join_command

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"