- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ apt_packages }}"
    state: present
    update_cache: yes
- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    state: present

- name: Install docker and its dependecies
  apt: 
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes
  notify:
    - docker status
- name: docker start
  service: 
    name: docker 
    state: started
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
  
- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
#    repo: deb https://apt.kubernetes.io/ kubernetes-{{ansible_distribution_release}} main
#apparently they don't even have bionic yet.
    state: present
    filename: kubernetes.list
- name: Install Kubernetes binaries
  apt: 
    name: "{{ k8s_packages }}"
    state: present
    update_cache: yes
- name: Configure node ip
  lineinfile:
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ ansible_default_ipv4.address }}
    create: yes
- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted